// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// dcombined
NumericVector dcombined(NumericVector mean1, NumericVector mean2, double sigma_normal, NumericVector nu, NumericVector sigma, NumericVector log_beta_precomp);
RcppExport SEXP studentMetaMean_dcombined(SEXP mean1SEXP, SEXP mean2SEXP, SEXP sigma_normalSEXP, SEXP nuSEXP, SEXP sigmaSEXP, SEXP log_beta_precompSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< NumericVector >::type mean1(mean1SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type mean2(mean2SEXP);
    Rcpp::traits::input_parameter< double >::type sigma_normal(sigma_normalSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type nu(nuSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type sigma(sigmaSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type log_beta_precomp(log_beta_precompSEXP);
    __result = Rcpp::wrap(dcombined(mean1, mean2, sigma_normal, nu, sigma, log_beta_precomp));
    return __result;
END_RCPP
}
