// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// optimise_overlap
NumericVector optimise_overlap(NumericVector meann, double sigman, double nu, double means, double sigmas);
RcppExport SEXP studentMetaMean_optimise_overlap(SEXP meannSEXP, SEXP sigmanSEXP, SEXP nuSEXP, SEXP meansSEXP, SEXP sigmasSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< NumericVector >::type meann(meannSEXP);
    Rcpp::traits::input_parameter< double >::type sigman(sigmanSEXP);
    Rcpp::traits::input_parameter< double >::type nu(nuSEXP);
    Rcpp::traits::input_parameter< double >::type means(meansSEXP);
    Rcpp::traits::input_parameter< double >::type sigmas(sigmasSEXP);
    __result = Rcpp::wrap(optimise_overlap(meann, sigman, nu, means, sigmas));
    return __result;
END_RCPP
}
