# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

dcombined <- function(mean1, mean2, sigma_normal, nu, sigma, log_beta_precomp) {
    .Call('studentMetaMean_dcombined', PACKAGE = 'studentMetaMean', mean1, mean2, sigma_normal, nu, sigma, log_beta_precomp)
}

