# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

optimise_overlap <- function(meann, sigman, nu, means, sigmas) {
    .Call('studentMetaMean_optimise_overlap', PACKAGE = 'studentMetaMean', meann, sigman, nu, means, sigmas)
}

