# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

dnorms <- function(mean1, mean2, sigma) {
    .Call('studentMetaMean_dnorms', PACKAGE = 'studentMetaMean', mean1, mean2, sigma)
}

dstud <- function(mean1, mean2, nu, sigma, log_beta_precomp) {
    .Call('studentMetaMean_dstud', PACKAGE = 'studentMetaMean', mean1, mean2, nu, sigma, log_beta_precomp)
}

